language: python
python:
  - '3.6'

install:
  - pip install --upgrade nox-automation

script:
  - nox -s update_dashboard
  - touch docs/.nojekyll

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: dashboard
  skip_cleanup: true
  email: yanhuil@google.com # To satisfy the CLA check.
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
