language: python
python:
- '3.6'
install:
- pip install --upgrade nox-automation
script:
- nox -s update_dashboard
- touch dashboard/.nojekyll
branches:
  only:
  - master
deploy:
  provider: pages
  local_dir: dashboard
  skip_cleanup: true
  email: yanhuil@google.com
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
before_install:
- if [ -n "encrypted_415d6cfcbdfb_iv" ]; then
    openssl aes-256-cbc -K $encrypted_415d6cfcbdfb_key -iv $encrypted_415d6cfcbdfb_iv
    -in python-compatibility-tools.json.enc -out python-compatibility-tools.json -d;
  fi
- export GOOGLE_APPLICATION_CREDENTIALS=python-compatibility-tools.json
